### ISSUE TITLE
Add possibility to block facts/factsets with regexp or some subgroup/wildcard.

### ISSUE THREAD

**Issue by sharewax** [puppetlabs/facter#2713]
## Use Case
Currently I observe that a lot of facts/factsets pushed in puppetdb which is not needed. For example I don't need info about virtual interfaces on host, like cali, docker, veth and etc. Currently I can block only all interfaces in blocklist like "networking.interfaces" but not `"networking.interfaces.cali.*", "networking.interfaces.veth.*", "networking.interfaces.docker.*", "networking.interfaces.macvtap.*", "networking.interfaces.vnet.*", "networking.interfaces.tunl.*"`.
Also it's impossible to block on puppetdb level because of new structure with hashes instead of flat sctructure.
Also block doesn't work for 3rd level of hierarchy like `"networking.interfaces.docker0"` doesn't block this fact, only whole `"networking.interfaces"` works.

## Describe the Solution You Would Like
I would like to store less facts in puppetdb and/or output in facter output. It would be perfect if we can block facts/facts block by wildcard/regexp (like in puppetdb with facts-blocklist-type = regex).

**Comment by joshcooper** [comment]
@sharewax we have an issue filed to allow portions of structured fact values to be filtered in https://github.com/puppetlabs/facter/issues/2658 I think that would solve your use case.

> it's impossible to block on puppetdb level because of new structure with hashes instead of flat sctructure.

This sounds like a bug in puppetdb. I would expect it's possible to block structured facts to limit the amount of data stored there, especially since legacy facts are disabled by default in Puppet 8. Maybe the `facts-blocklist-type` setting has never worked with structured facts? 

Based on that I'm thinking we should close this as a dup of 2658 and file a separate issue for puppetdb. Thoughts?

**Comment by sharewax** [comment]
Yes, the #2658 is looks as the same here.
I've created ticket in [puppetdb space](https://github.com/puppetlabs/puppetdb/issues/3975), thank you. Maybe you can extend more info in this ticket.

**Comment by joshcooper** [comment]
Thanks for adding the puppetdb ticket, I'm going to close this as a dup of #2658

> Maybe you can extend more info in this ticket.

I didn't quite get this part? Could you add any details that you think are missing from this ticket to 2658?

**Comment by sharewax** [comment]
all is ok, maybe I just think that info  (like in https://github.com/puppetlabs/facter/issues/2658) for puppetdb will be also useful

**Comment by Szparki** [comment]
@sharewax I am having the same issue with K8s and docker interfaces. Have you found a solution?

**Comment by sharewax** [comment]
@Szparki unfortunately no.
