### ISSUE TITLE
provide a schema for each facter release

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/facter#2730]
## Use Case

We've some tests in facterDB to validate factsets. Some factsets are created by hand to generated. To ensure they are complete/correct, it would be nice to have a schema we can use to validate the factsets.

## Describe the Solution You Would Like

Provide a schema for each facter version factset.

**Comment by joshcooper** [comment]
Facter currently does have a schema https://github.com/puppetlabs/facter/blob/main/lib/schema/facter.yaml though it is likely in need of updating. Facter 3 also had a test to [verify the output matched the schema](https://github.com/puppetlabs/facter/blob/d613aa1492b0da6f78a99379576f85cee4dd2af8/lib/tests/facts/schema.cc#L745-L746), but we seem to have lost that in Facter 4. So for this issue, I think we should:

- [ ] Update the facter.yaml schema to include any facts added since the schema was last updated in 71be25dd9aeee441f7b88680960e0ee31d7d5e95
- [ ] Add CONTRIBUTING.md to mention that new facts need to be added to the schema. Currently we're inheriting the org-wide version.
- [ ] Add an acceptance test the facter output conforms to the schema on each platform

**Comment by AriaXLi** [comment]
This is addressed in #2746

**Comment by joshcooper** [comment]
Fixed in https://github.com/puppetlabs/facter/pull/2746
